# Black        0;30     Dark Gray     1;30
# Red          0;31     Light Red     1;31
# Green        0;32     Light Green   1;32
# Brown/Orange 0;33     Yellow        1;33
# Blue         0;34     Light Blue    1;34
# Purple       0;35     Light Purple  1;35
# Cyan         0;36     Light Cyan    1;36
# Light Gray   0;37     White         1;37

NC='\033[0m'; Black='\033[m0;30'

usage(){
	case $1 in
	download_SRA)
echo -e "
==========
usage: download_SRA -f <LIST of STRING> -o <PATH> -n <LIST of STRING> -t [INT]

general infos: automatic download on Sequence Read Archive database

-- Mandatory arguments:
    -f      STRING  :    List of SRA IDs to download. example: 
                        (\"STR1\" \"STR2\" ... \"STRn\")
    -o      PATH    :    Set the Output directory, where you will find the 
                        FASTQ files created by this program.
    -n      STRING  :    Set the prefix for downloaded fastq

-- optional arguments :
    -t     INT      :    Set the number of threads to use. (default: 1)
\n";;
	mapping_Fastq_bowtie2)
echo -e "
==========
usage: mapping_Fastq_bowtie2 -id <PATH> -od <PATH>
       -keepDup <\"auto\"/\"all\"/INT> -s [INT] -pr [INT]
       -in [PATH] -size [PATH] [-debug] [-multialign]

general infos: aligns FASTQ files (single-end or paired-end) with
Bowtie2, filters low-quality/multimapped reads, converts SAM to
sorted/indexed BAM, removes PCR duplicates and generates mapping
statistics (duplication rates included)

-- Mandatory arguments:
    -id     PATH    :    Input directory containing the FASTQ
                         files to align.
    -od     PATH    :    Set the Output directory, where you
                         will find the processed BAM files and
                         mapping statistics.
    -keepDup STRING :    Set the duplication level to keep
                         (\"auto\", \"all\", or an integer, as in
                         MACS3 filterdup).

-- optional arguments :
    -s      INT     :    Set the seed value used by Bowtie2.
                         (default: 1254)
    -pr     INT     :    Set the number of threads to use.
                         (default: 1)
    -in     PATH    :    Set the path to the Bowtie2 index.
    -size   PATH    :    Set the path to the chromosome size
                         file. 
    -debug          :    Enable debug mode (keeps intermediate
                         files).
    -multialign     :    Allow multimapped reads to be kept
                         (\"canbe\") instead of filtered out
                         (default: filtered out).
\n";;
	main_mapping_Fastq)
echo -e "
==========
usage: main_mapping_Fastq -fd <PATH> -md <PATH> -f1 <FILE>
       -n <STRING> -f2 [FILE] -s [INT] -pr [INT]
       -dedup [INT/\"all\"/\"auto\"] -size [FILE] -in [PATH]
       [-debug] [-multialign]

general infos: wrapper around mapping_Fastq_bowtie2. Validates
the input arguments, prepares the required files, and runs the
Bowtie2 mapping of a FASTQ dataset (single-end or paired-end)

-- Mandatory arguments:
    -fd     PATH    :    Path to the directory containing the
                         FASTQ files.
    -md     PATH    :    Path to the directory where mapping
                         results will be stored.
    -f1     FILE    :    FASTQ file for pair 1, or for
                         single-end reads.
    -n      STRING  :    Name of the dataset (used for naming
                         output files).

-- optional arguments :
    -f2     FILE    :    FASTQ file for pair 2 (paired-end
                         reads only).
    -s      INT     :    Seed for random number generation.
                         (default: 1254)
    -pr     INT     :    Number of threads to use for
                         processing. (default: 1)
    -dedup  INT     :    Deduplication setting (an integer,
                         \"all\" or \"auto\"). (default: 1)
    -size   FILE    :    Path to the chromosome size file.
    -in     PATH    :    Path to the Bowtie2 index files.
    -debug          :    Enable debug mode (additional
                         logging).
    -multialign     :    Allow multi-alignment of reads.
\n";;
	peakcalling_MACS2)
echo -e "
==========
usage: peakcalling_MACS2 -id <PATH> -od <PATH> -g [FILE] -s [INT] -phs [INT]
       -t [INT] -kd [STRING] -bl [PATH] -size [PATH] -r [BOOL]

general infos: perform peak calling and peak filtration (forbidden regions)

-forbidden regions: those are regions that present a high coverage in control.
         Those regions are therefore removed from analysis.

-- Mandatory arguments:
    -id     PATH    :    Set the directory where the BAM files are stored
    -od     PATH    :    Set the Output directory, where you will find the 
                         BEDGRAPH and NarrowPeak files generated by this 
                         program.

-- optional arguments :
    -g      INT     :    Set the genome length to use as reference for peak 
                         calling. (default: 120000000)
    -s      INT     :    Set the seed for the random (default: 1254)
    -phs    INT     :    Peaks half size. Peaks detected by MACS2 will be 
                         resized to this length, centered around maximum of 
                         coverage. (default: 200)
    -t      INT     :    number of threads to use for MACS2
    -kd     STRING  :    Maximum number of duplicated reads to keep in 
                         analysis. (default: 1)
    -bl     PATH    :    File, in bed format, used to filter out forbidden 
                         regions. (default: Greenscreen)
    -size   PATH    :    fai file of the genome used.
    -r      BOOL    :    whether or not the directory should be deleted for 
                         re-analysis from the start. (default: false)
\n";;
	peakcalling_MACS3)
echo -e "
==========
usage: peakcalling_MACS3 -id <PATH> -od <PATH> -r <BOOL>
       -g [INT] -s [INT] -phs [INT] -t [INT] -kd [STRING]
       -bl [PATH] -size [PATH] -cs [PATH] --llocal [INT]
       --slocal [INT] --factork [INT] --qval [FLOAT]
       --minlen [INT] --minfold [INT] --maxfold [INT]
       [-diag BOOL]

general infos: peak calling on aligned reads with MACS3,
using a control track for comparison and a blacklist of
regions to exclude

-- Mandatory arguments:
    -id     PATH    :    Input directory containing the
                         BAM aligned data files.
    -od     PATH    :    Set the Output directory, where you
                         will find the peak calling results.
    -r      BOOL    :    Set to true/false whether the
                         analysis should be redone.

-- optional arguments :
    -g      INT     :    Set the mappable genome length.
                         (default: 120000000)
    -s      INT     :    Set the random seed. (default: 168159)
    -phs    INT     :    Set the peaks half size. (default: 200)
    -t      INT     :    Set the number of threads to use.
                         (default: 1)
    -kd     STRING  :    Set the duplication level to keep
                         (\"auto\", \"all\", or an integer, as in
                         MACS3 filterdup). (default: 1)
    -bl     PATH    :    Set the path to the blacklist file.
    -size   PATH    :    Set the path to the chromosome size
                         file.
    -cs     PATH    :    Set the path to the control stats
                         file. (default: NA)
    --llocal INT    :    Set the local lambda large window
                         size. (default: 5000)
    --slocal INT    :    Set the local lambda small window
                         size. (default: 500)
    --factork INT   :    Set the factor for k. (default: 3)
    --qval  FLOAT   :    Set the q-value cutoff. (default: 0.05)
    --minlen INT    :    Set the minimum peak length.
                         (default: 100)
    --minfold INT   :    Set the minimum fold enrichment.
                         (default: 5)
    --maxfold INT   :    Set the maximum fold enrichment.
                         (default: 50)
    -diag   BOOL    :    Enable diagnostic mode (true/false).
                         (default: false)
\n";;
	peakcalling_GOPeaks)
echo -e "
==========
usage: peakcalling_GOPeaks -id <PATH> -od <PATH> -s [INT]
       -phs [INT] -t [INT] -size [PATH]

general infos: peak calling on aligned reads with GOPeaks,
Adapted for Cut&Tag and Cut&Run analyses

-- Mandatory arguments:
    -id     PATH    :    Input directory containing the
                         aligned BAM data files.
    -od     PATH    :    Set the Output directory, where you
                         will find the peak calling results.

-- optional arguments :
    -s      INT     :    Set the random seed. (default: 6318)
    -phs    INT     :    Set the peaks half size. (default: 200)
    -t      INT     :    Set the number of threads to use.
                         default: 2)
    -size   PATH    :    Set the path to the chromosome size (FAI)
                         file.
\n";;
	main_peakcalling)
echo -e "
==========
usage: main_peakcalling -id <PATH> -od <PATH> -nc <STRING>
       -cd [PATH] -g [INT] -top [INT] -ps [INT] -size [PATH]
       -bl [PATH] -mspc [INT%] -pm [STRING] -s [INT] -t [INT]
       --keep-dup [INT] [-r] [-diag] [--SD-filtering]
       --llocal [INT] --factork [FLOAT] --qval [FLOAT]
       --minfold [INT] --maxfold [INT] --minlen [INT]
       --weak [FLOAT] --strong [FLOAT]

general infos: wrapper performing peak calling (MACS3 or
GOPeaks), building consensus peaks from replicates with MSPC,
resizing them and generating coverage files

-- Mandatory arguments:
    -id     PATH    :    Set the [LIST] of directories where the BAM files are
                         stored
    -od     PATH    :    Set the [LIST] of directories where the BAM files for
                         the control sets are stored
    -nc     STRING  :    Set the name of the final output directory where the
                         consensus NarrowPeak & BEDGRAPH will be stored
-- optional arguments :
    -cd     PATH    :    List of path(s) to the control data
                         directory. (default: NA)
    -g      INT     :    Set the mappable genome length.
                         (default: 120000000)
    -top    INT     :    Set the maximum number of peaks to
                         retain. (default: 0, no limit)
                         Peaks will be ordered by p-value before the 
                         cut-off is applied
    -ps     INT     :    Set the peak size. (default: 400,
                         i.e. peak half size of 200)
    -size   PATH    :    Set the path to the genome size file.
    -bl     PATH    :    Set the path to the blacklist file.
    -mspc   INT%    :    Set the percentage of replicates necessary to 
                         consider a peak as a consensus (ex: 100: all 
                         replicates must have the same peak to consider it as
                         consensual). Accepted values: 1 to 100.(default: 100)
    -pm     STRING  :    Set the peak caller to use (MACS3 or
                         GOPeaks). (default: MACS3)
    -s      INT     :    Set the random seed. (default: 168159)
    -t      INT     :    Set the number of threads to use.
                         (default: 8)
    --keep-dup INT  :    Set the duplicate reads to keep.
                         (default: 1)
    -r              :    Redo the analysis. (default: false)
    -diag           :    Enable diagnostic mode.
                         (default: false)
    --SD-filtering  :    Filter peaks using the standard
                         deviation of coverages. (default: off)
    --llocal INT    :    Set the large local background size,
                         used to discriminate from noise
                         signal. (default: 5000)
    --factork FLOAT :    Filtering value applied on the ratio between sample 
                         and control ( coverage in sample must be at least 
                         FLOAT times higher than control). This threshold is 
                         applied twice. First on results by MACS3, seconds on
                         CPM values computed by this function. (default: 3)
    --qval  FLOAT   :    Set the q-value threshold for peak
                         detection. (default: 0.05)
    --minfold INT   :    Set the minimum fold change for peak
                         detection. (default: 5)
    --maxfold INT   :    Set the maximum fold change for peak
                         detection. (default: 50)
    --minlen INT    :    Set the minimum length for peak
                         detection. (default: 100)
    --weak  FLOAT   :    Set the weak p-value threshold for
                         MSPC. (default: 1e-5)
    --strong FLOAT  :    Set the strong p-value threshold for
                         MSPC. (default: 1e-9)
\n";;
	replicates_comparisons)
echo -e "
==========
usage: replicates_comparisons -p <PATH> -nb <INT> -od <PATH>
       -gd <PATH> -n <STRING> -c [STRING]

general infos: compares replicates for peak calling and
coverage computation, supporting \"Not Input Normalized\" and
\"Input Re-Normalized\" normalization methods

-- Mandatory arguments:
    -p      PATH    :    Set the path to the consensus peaks
                         file.
    -nb     INT     :    Set the number of replicates in the
                         sample.
    -od     PATH    :    Set the Output directory for results.
    -gd     PATH    :    Set the General directory containing
                         the \`Peakcalling\` and \`Mapping\`
                         subdirectories.
    -n      STRING  :    Set the name of the sample.

-- optional arguments :
    -c      STRING  :    Set the color for dots in plots (hex
                         code, e.g. \`#FF0000\` or \`FF0000\`).
                         (default: #000000)
\n";;
	pairwize_comparison)
echo -e "
==========
usage: pairwize_comparison -n1 <STRING> -n2 <STRING>
       -od <PATH> -id <PATH> -id2 [PATH] -f [INT] -he [INT]
       -bd [PATH] -bd2 [PATH] -p1 [PATH] -p2 [PATH]
       -gcov [STRING] -rep1 [LIST] -rep2 [LIST]
       -ctrl1 [LIST] -ctrl2 [LIST] [-ext] -c1 [STRING]
       -c2 [STRING] -cn [STRING] -keep [STRING] -th [FLOAT]

general infos: performs pairwise comparison of two datasets
(e.g. ChIP-seq replicates or conditions): merges peaks,
computes coverage (RPKM) in peaks and libraries, and
generates comparative plots. Supports replicates, control
samples and edgeR differential analysis when both datasets
have replicates.

-- Mandatory arguments:
    -n1     STRING  :    Set the name of the first dataset.
    -n2     STRING  :    Set the name of the second dataset.
    -od     PATH    :    Set the Output directory for results.
    -id     PATH    :    Set the General data directory (peak
                         calling directory) for the first
                         dataset.

-- optional arguments :
    -id2    PATH    :    Set the General data directory for
                         the second dataset. (default: same as
                        -id)
    -f      INT     :    Set the minimum coverage required in
                         both samples to consider a peak.
                         (default: 0)
    -he     INT     :    Set the minimum height required in
                         both samples to consider a peak.
                         (default: 0)
    -bd     PATH    :    Set the General BAM directory for the
                         first dataset.
    -bd2    PATH    :    Set the General BAM directory for the
                         second dataset. (default: same as -bd)
    -p1     PATH    :    Set the path to the peaks file for the
                         first dataset. (default: NA)
    -p2     PATH    :    Set the path to the peaks file for the
                         second dataset. (default: NA)
    -gcov   STRING  :    Set whether to compute reads count
                         from BAM at each peak (\"yes\" or
                         \"no\"). (default: yes)
    -rep1   LIST    :    Set the list of replicate names for
                         the first dataset.
    -rep2   LIST    :    Set the list of replicate names for
                         the second dataset.
    -ctrl1  LIST    :    Set the list of control BAM files for
                         the first dataset. (default: null)
    -ctrl2  LIST    :    Set the list of control BAM files for
                         the second dataset. (default: null)
    -ext            :    Activate extended peaks mode.
                         (default: false)
    -c1     STRING  :    Set the color for the first dataset.
                         (default: #2A9D8F)
    -c2     STRING  :    Set the color for the second dataset.
                         (default: #B8475C)
    -cn     STRING  :    Set the neutral color for common
                         peaks. (default: #BEBAB7)
    -keep   STRING  :    Keep original peaks to compute
                         additional RiP before merging (\"yes\"
                         or \"no\"). (default: no)
    -th     FLOAT   :    Set the threshold for fold change to
                         consider a peak as specific to one of
                         the two datasets (e.g. 2 for 2-fold
                         change). (default: 1)
\n";;
	compute_rpkmrip_rpkmril)
echo -e "
==========
usage: compute_rpkmrip_rpkmril -p <PATH> -bd <LIST of PATH>
       -pd <LIST of PATH> -sn <LIST of STRING> -m <STRING>
       -o <PATH> -g [STRING]

general infos: Takes a bed file with peaks coordinates (e.g. merged peaks
               of two conditions yield by pairwize_comparison)  to recalculate
			   normalized RPKM for each sample you provided.
			   RPKM is normalized as read per kilo per million of:
					- reads in peaks (RPKMRIP)
			        - OR in library (RPKMRIL). 
					(By library we mean: all properly mapped reads and more 
					precisely the number of 'filtTags' calculated my MACS3.
               Nota Bene: this function may need up to 50G mem for large bam file

-- Mandatory arguments:
    -p      PATH    :    Set the path to the file containing
                         consensus peaks.
    -bd     LIST    :    Set the list of directories
                         containing BAM files for each sample.
    -pd     LIST    :    Set the list of directories
                         containing peak calling results for
                         each sample.
    -sn     LIST    :    Set the list of sample names to
                         process.
    -m      STRING  :    Set the normalization mode
                         (\"inPeaks\" or \"inLibs\").
    -o      PATH    :    Set the Output directory where files
                         will be saved.

-- optional arguments :
    -g      STRING  :    Set whether to compute coverage
                         (\"yes\" or \"no\"). (default: yes)
\n";;
	compute_motif)
echo -e "
==========
usage: compute_motif -p <PATH> -n <STRING> -od <PATH>
       -c [INT] -g [PATH] -ls [INT] -nm [INT] [-t] -mim [INT]
       -mam [INT] [-pal] -stffm [INT] -s [INT] -top [INT]
       -neg [PATH] -cutoff [FLOAT]

general infos: performs motif discovery and analysis using
MEME and TFFM: prepares sequence datasets, runs MEME for
motif discovery, and generates Position Frequency Matrices
(PFM) and TFFM models. Supports both palindromic and
non-palindromic motifs.

PWM: Position Weight Matrix
TFFM: Transcription Factor Flexible Model

-- Mandatory arguments:
    -p      PATH    :    Set the path to the BED file
                         containing peaks.
    -n      STRING  :    Set the name for the sub-directory
                         and output files.
    -od     PATH    :    Set the Output directory for results.

-- optional arguments :
    -c      INT     :    Set the column number in the input
                         BED file that gives sequence coverage
                        (RPKM). (default: 0)
    -g      PATH    :    Set the path to the genome FASTA
                         file.
    -ls     INT     :    Set the size of the learning set.
                         (default: 600)
    -nm     INT     :    Set the number of PWM motifs to
                         generate. (default: 1)
    -t              :    Transpose the PWM motif if required.
                         (default: false)
    -mim    INT     :    Set the minimum length for motifs.
                         (default: 6)
    -mam    INT     :    Set the maximum length for motifs.
                         (default: 15)
    -pal            :    Activate palindromic mode for motif
                         discovery. (default: false)
    -stffm  INT     :    Set the PFM index used for TFFM
                         computation. (default: 0)
    -s      INT     :    Set the seed for random number
                         generation. (default: 1254)
    -top    INT     :    Set the maximum number of peaks to
                         consider for the testing set.
                         (default: 0)
    -neg    PATH    :    Set the path to the control file
                         (negative set). (default: NA)
    -cutoff FLOAT   :    Set the fraction of sequences having
                         at least one motif to consider a motif
                         as valid. (default: 0.333)
\n";;
	prep_annotation)
echo -e "
==========
usage: prep_annotation -n <FILE> -o <PATH> -p [INT]
       -g [FILE] -s [FILE]

general infos: prepares genome annotation files by extracting
and formatting promoter, intronic, intergenic and exonic
regions from a GFF3 file, generating a comprehensive
annotation file for downstream analysis (peak annotation,
genomic feature enrichment); can generate a FAI file if not
provided. Used to generate negtaive peaks sets. 

-- Mandatory arguments:
    -n      FILE    :    Set the path to the GFF3 annotation
                         file of the genome.
    -o      PATH    :    Set the path to the output
                         annotation file.

-- optional arguments :
    -p      INT     :    Set the length of promoter regions to
                         extract (in bp). (default: 1000)
    -g      FILE    :    Set the path to the genome FASTA
                         file. Required if -s is not provided.
    -s      FILE    :    Set the path to the genome size file
                         (FAI format). Required if -g is not
                         provided.
\n";;
	compute_NS)
echo -e "
==========
usage: compute_NS -p <FILE> -n <STRING> -g <FILE> -od <PATH>
       -anf <FILE> -nb [INT] -ws [INT] -gc [FLOAT] -lt [INT]
       -mp [INT] -c [INT] -s [INT] [--timeout] [-st]

general infos: generates negative sets of genomic regions
for comparative analysis, using a Python script
(negative_set_script) that matches GC content and other
characteristics of the input peak regions; supports a
standard mode and a faster, less precise simplified mode

-- Mandatory arguments:
    -p      FILE    :    Set the path to the BED file
                         containing peak regions.
    -n      STRING  :    Set the prefix for the output files.
    -g      FILE    :    Set the path to the genome FASTA
                         file.
    -od     PATH    :    Set the Output directory for results.
    -anf    FILE    :    Set the path to the annotation file
                         (BED format).

-- optional arguments :
    -nb     INT     :    Set the number of negative sets to
                         generate. (default: 1)
    -ws     INT     :    Set the window size for negative set
                         generation. (default: 250)
    -gc     FLOAT   :    Set the maximum allowed difference in
                         GC content between positive and
                         negative sets. (default: 0.03)
    -lt     INT     :    Set the number of regions to generate
                         per annotation type. (default: 1000)
    -mp     INT     :    Set the maximum number of peaks to
                         retain for negative set generation.
                         (default: 15000)
    -c      INT     :    Set the column number in the input
                         BED file that gives sequence coverage
                         (RPKM). (default: 0)
    -s      INT     :    Set the random seed for
                         reproducibility. (default: 1254)
    --timeout       :    Activate timeout mode: if the
                         standard mode takes too long (>15 min
                         per negative set), switch to the
                         simplified mode. (default: false)
    -st             :    Simple_type option. Simplify the types used by this 
                         function, from complex dual type (ex: Promoter+5'UTR) 
                         to unique type (ex: Promoter or 5'UTR; depending of 
                         higher overlap). This option can be used when this 
                         function crashes because it fails to find suitable 
                         negative regions.
\n";;
	generate_weighted_fasta)
echo -e  "
==========
usage: generate_weighted_fasta -f <FILE> -c [INT] -s <INT> -o <PATH> 
       -p <STRING> - g <FILE>

general infos:  a function called by compute_kmer to generate a 
                fasta where each sequence (peak) is weighted 
                (written in the header name). The weight can be 
                the coverage value (RPKM). This weight can be used
                by the KMAC tool in compute_kmer.

-- Mandatory arguments:
    -f     FILE     :    name of file containing peaks coordinates (bed)
    -s     INT      :    number of sequence to be used for training.
    -o     PATH     :    Set the Output directory.
    -p     STRING   :    A prefix to name the output of KMAC (this is dealt 
                         with the -n1 [-n2] argument(s) in compute_kmer.

-- optional arguments :
    -c     INT      :    Column number with peak coverage value. This is to 
                         be used to weight sequences by KMAC in compute_kmer. 
                         Set to '0' by default (weighting is not possible
                         in this case)
    -g     FILE     :    (path)/name of genome file. Default is TAIR10.
\n";;
	compute_DNAshape)
echo -e "
==========
usage: compute_DNAshape -f <FILE> -m <FILE> -o <PATH>
       -e [INT] -ls [INT] -n [STRING] -c [INT] -g [FILE]
       -anf [FILE] -ws [INT] -gc [FLOAT] -lt [INT] -top [INT]
       -s [INT]

general infos: prepares training and testing datasets for
DNA shape analysis: splits input peak regions into training
and testing sets, generates negative sets, extracts FASTA
sequences for foreground and background regions, trains a
DNA shape classifier (TFFM or PWM) and generates heatmaps of
DNA shape features

doi: https://doi.org/10.1016/j.cels.2016.07.001
PMID: 27546793)

-- Mandatory arguments:
    -f      FILE    :    Set the path to the BED file
                         containing foreground peak regions.
    -m      FILE    :    Set the path to the matrix file (PFM
                         or TFFM format).
    -o      PATH    :    Set the Output directory for results.

-- optional arguments :
    -e      INT     :    Extension of DNAshape modeling to include upstream and
                         downstream base pairs relative to the given matrix 
                         (default: 0)
    -ls     INT     :    Set the number of sequences for the
                         learning set. (default: 250)
    -n      STRING  :    Set the prefix for output files.
    -c      INT     :    Set the column number in the input
                         BED file that gives sequence coverage
                         (RPKM). (default: 0)
    -g      FILE    :    Set the path to the genome FASTA
                         file.
    -anf    FILE    :    Set the path to the annotation file
                         (BED format).
    -ws     INT     :    Size of the window used to slice the genome. Ideally 
                         the it should be set 30-50 higher than the smallest
                         peak in the positive set (default: 250)  
    -gc     FLOAT   :    Set the maximum allowed difference in
                         GC content between positive and
                         negative sets. (default: 0.03)
    -lt     INT     :    Set the number of regions to generate
                         per annotation type. (default: 1000)
    -top    INT     :    Set the maximum number of peaks to
                         consider for the testing set.
                         (default: 0)
    -s      INT     :    Set the random seed for
                         reproducibility. (default: 1254)
\n";;
	compute_SeqConv)
echo -e "
==========
usage: compute_SeqConv -p <FILE> -ps <INT> -ns <FILE>
       -n <STRING> -g <FILE> -od [PATH] -sf [FILE] -s [INT]
       -split [INT]

general infos: prepares a dataset of peak sequences, trains
a SeqConv model for motif discovery, and generates a motif
logo from the model's predictions using a Python-based
pipeline

-- Mandatory arguments:
    -p      FILE    :    Set the path to the BED file
                         containing peak coordinates.
    -ps     INT     :    Set the size of peaks in base pairs.
                         (default: 200)
    -ns     FILE    :    Set the path to the BED file
                         containing negative set coordinates.
    -n      STRING  :    Set the prefix for output directory
                         and files.
    -g      FILE    :    Set the path to the genome FASTA
                         file.

-- optional arguments :
    -od     PATH    :    Set the Output directory where
                         results will be saved.
    -sf     FILE    :    Set the path to the chromosome size
                         file.
    -s      INT     :    Set the random seed for
                         reproducibility. (default: 1254)
    -split  INT     :    Set the percentage of data to use for
                         the training set. (default: 80)
\n";;
	compute_kmer)
echo -e "
==========
usage: compute_kmer -b1 <FILE> -n1 <STRING> -kwi <INT>
       -kmi <INT> -kma <INT> -o <PATH>
       (-split <INT> | -ls <INT>) -g [FILE] -b2 [FILE]
       -ktop [INT] -r [STRING]

general infos: performs k-mer analysis using the KMAC
program (GEM suite) to identify enriched k-mer sets in a
positive sequence set, optionally compared against a
negative set. Splits the input into training/testing sets
(by percentage or by top N sequences), extracts FASTA
sequences, runs KMAC, then moves and organizes its outputs.

-- Mandatory arguments:
    -b1     FILE    :    Set the BED file for positive
                         sequences.
    -n1     STRING  :    Set the name of the first condition
                         (usually the positive set).
    -kwi    INT     :    Set the k-mer window size.
    -kmi    INT     :    Set the minimum k-mer length.
    -kma    INT     :    Set the maximum k-mer length.
    -o      PATH    :    Set the Output directory.
    -split  INT     :    Set the percentage of sequences to
                         use for the training set. Mutually
                         exclusive with -ls; exactly one of
                         the two must be provided.
    -ls     INT     :    Set the number of (top, non-shuffled)
                         sequences to use for the training set.
                         Mutually exclusive with -split;
                         exactly one of the two must be
                         provided.

-- optional arguments :
    -g      FILE    :    Set the path to the genome file.
    -b2     FILE    :    Set the BED file for negative
                        sequences. If omitted, KMAC runs
                        without a negative set.
    -ktop   INT     :    Set the number of top k-mers to
                        report. (default: 5)
    -r      STRING  :    Set the run ID, used to name the
                        KMAC outputs.
\n";;
	compute_ROCS)
echo -e "
==========
usage: compute_ROCS -p <LIST of FILE> -ns <LIST of FILE>
       -m <LIST of FILE> -n <LIST of STRING> -od <PATH>
       -g [FILE] [-pc] -d [STRING] -ol [INT] -or [INT]
       -nKSM [INT] -sKSM [STRING] -ps [INT]
       -color [LIST of STRING] -s [INT] -fpr_lim [FLOAT]

general infos: computes and plots ROC curves for various
sequence models (TFFM, K-mer/KSM, DNAshape, PWM/dimer, and
SeqConv), evaluating how well each model distinguishes
positive from negative sequence sets

-- Mandatory arguments:
    -p      LIST    :    Set the list of BED or FASTA files
                         containing peak sequences.
    -ns     LIST    :    Set the list of BED or FASTA files
                         containing negative sequences.
    -m      LIST    :    Set the list of matrix files (TFFM,
                         K-mer, PWM or SeqConv).
    -n      LIST    :    Set the list of names associated
                         with each peak/negative set/matrix
                         combination.
    -od     PATH    :    Set the Output directory for results.

-- optional arguments :
    -g      FILE    :    Set the path to the genome FASTA
                         file.
    -pc             :    Activate Pocc mode for PWM analysis.
                         (default: false)
    -d      STRING  :    Set the dimer conformation for PWM
                         analysis. (default: Mono)
    -ol     INT     :    Set the left offset for peak
                         extension. (default: 0)
    -or     INT     :    Set the right offset for peak
                         extension. (default: 0)
    -nKSM   INT     :    Set the k-mer set (m0, m1, m2, etc.)
                         to use in the KSM search. (default: 0)
    -sKSM   STRING  :    Set the k-mer score method (SUM,
                         BEST or MEAN). (default: BEST)
    -ps     INT     :    Set the size of peaks in base pairs.
                         (default: 200)
    -color  LIST    :    Set the list of colors for ROC
                         curves. (default: a predefined list
                         of colors)
    -s      INT     :    Set the seed for shuffling peaks and
                         negative sets. (default: 1234)
    -fpr_lim FLOAT  :    Set the limit for False Positive
                         Rate in ROC curves. (default: 1, full
                         ROC)
\n";;
	compute_distribution)
echo -e "
==========
usage: compute_distribution -m <FILE> -n <STRING> -od <PATH>
       -g [FILE] -r [INT] -c [LIST of STRING] [--all]

general infos: calculates and visualizes the distribution of
motif scores (TFFM or PWM) across a genome; processes each
chromosome in parallel, samples a subset of the scores, and
creates an interactive distribution plot, useful for
analyzing global motif occurrence and setting thresholds

-- Mandatory arguments:
    -m      FILE    :    Set the path to the matrix file
                         (TFFM in .xml format or PWM in .pfm
                         format).
    -n      STRING  :    Set the prefix for output files and
                         directories.
    -od     PATH    :    Set the Output directory for results.

-- optional arguments :
    -g      FILE    :    Set the path to the genome FASTA
                         file.
    -r      INT     :    Set the identifier for the
                         interactive plot request. (default: 0)
    -c      LIST    :    Set the list of chromosomes to
                         analyze. (default: chr1 chr2 chr3
                         chr4 chr5)
    --all           :    Use all scores for the distribution
                         plot, without sampling. (default:
                         false, 10%% of scores are sampled)
\n";;
	compute_space) 
echo -e "
==========
usage: compute_space -p <LIST of FILE> -m <LIST of FILE> -n <LIST of STRING> 
       -od <RESULT_DIR> -th <LIST of FLOAT> -thf [PATH] -maxy [INT] -miny [INT]
       -maxs [INT] -mins [INT] -ol [INT] -or [INT] -g [FILE] [-sym] 
       -color [LIST of STRING]

general infos: computes spacing analysis on peak files using PWM/TFFM. The 
               metric used to computed the enrichment and the statistical 
               relevance of the results is the Z-score 
               (doi: 10.1093/nar/gki624; PMID: 15933209). We highly suggest 
               that you use multiple threshold, based on genome wide scores
               distribution (computed in \"compute_distribution\" function),
               as they are a good starting point for this analysis. 

-- Mandatory arguments:
    -p     FILE     :    List of peak files (bed, narrowpeak format, or fasta 
                         files, or scores computed in \"compute_ROCS\" 
                         function). Example:(\"FILE1\" \"FILE2\" .. \"FILEn\")
    -m     FILE     :    List of matrices files (either TFFM or PWM). Example:
                         (\"FILE1\" \"FILE2\" ... \"FILEn\")
    -n     STRING   :    List of samples names for result files. 
                         (\"FILE1\" \"FILE2\" ... \"FILEn\")
    -od    PATH     :    Set the main output directory. a \"scores\" 
                         subdirectory containing intermediate files will be 
                         created. 
    -th    FLOAT    :    list of thresholds to use. (between 0-1 for TFFM
                         matrices & between -60-0 for PWMs). Choosing 
                         thresholds can be quite complicated. One way to get
                         satisfying threshold is to set them from a scores
                         distribution (see -thf). (default: (0))
                         Example: (\"FLOAT1\" \"FLOAT2\" ... \"FLOATn\")
                         
    -- optional arguments :
    -thf   PATH     :    Set a directory path for thresholds (output of 
                         compute_distribution function). Function will look for
                         \"scores_99_*_info.txt\" files. (default: \"null\")
    -miny  INT      :    minimum enrichment to display on y-axis. (default: 0)
    -maxy  INT      :    maximum enrichment to display on y-axis. (default: 0)
    -maxs  INT      :    maximum spacing to compute. For dimers (using 
                         monomeric matrices), a value between 30 to 50 bp 
                         seems a good start. For tetramers (using dimeric 
                         matrices) a value between 70 to 100 bp is a good 
                         start. You may adjust those values after your first
                         results. (default: 50)
    -mins  INT      :    minimum spacing to compute. Usually set to 0. You may
                         change this value if you add offsets, this will
                         prevent huge drop off in enrichment for the first 
                         spacings computed. (default: 0)
    -ol    INT      :    offset to apply on the left of the matrix used. This
                         argument (in addition to -or) allows to change the
                         way spacings are counted. This may be usefull when
                         you want to count space around a consensus sequence
                         or from the center of the matrix. Please, keep in
                         mind that it might create overlaping between 
                         positions of large information content, inducing a
                         biais not taken into consideration in this analysis.
                         We therefore suggest that you avoid this case.
    -or    INT      :    offset to apply on the right of the matrix used. See
                         -ol option for details.
    -g     FILE     :    Fasta of the genome used as reference.
    -sym            :    Precise if the matrix used is symetric. In that case,
                         instead of usual DR, ER & IR spacing, only the 
                         spacing is reported, since the matrix is not 
                         oriented. Note that TFFM are not symetric by design,
                         and this parameter will be ignored if used with TFFM.
                         (default: asymmetric matrix)
    -color STRING   :    List of color for graphical representation. 
\n";;
	spacing_2TFs) 
echo -e "
==========
usage: spacing_2TFs -p <LIST of FILE> -ma <LIST of FILE> -mb <LIST of FILE> 
       -n <LIST of STRING> -od <RESULT_DIR> -tha <LIST of FLOAT> 
       -thb <LIST of FLOAT> -thfa [PATH] -thfb [PATH] -maxy [INT] -miny [INT]
       -maxs [INT] -mins [INT] -ol [INT] -or [INT] -ol2 [INT] -or2 [INT] 
       -g [FILE] [-sym] 

general infos: computes spacing analysis between different matrices paires
               (PWM/TFFM) on peak files. The metric used to computed the 
               enrichment and the statistical relevance of the results is 
               the Z-score (doi: 10.1093/nar/gki624; PMID: 15933209). We 
               highly suggest that you use multiple threshold, based on genome
               wide scores distribution (computed in \"compute_distribution\" 
               function), as they are a good starting point for this analysis. 

-- Mandatory arguments:
    -p     FILE     :    List of peak files (bed, narrowpeak format, or fasta 
                         files, or scores computed in \"compute_ROCS\" 
                         function). Example:(\"FILE1\" \"FILE2\" .. \"FILEn\")
    -ma     FILE     :   First list of matrices files (either TFFM or PWM). 
                         Example: (\"FILE1\" \"FILE2\" ... \"FILEn\")
    -mb     FILE     :   Second list of matrices files (either TFFM or PWM). 
                         Example: (\"FILE1\" \"FILE2\" ... \"FILEn\")
    -n     STRING   :    List of samples names for result files. 
                         (\"FILE1\" \"FILE2\" ... \"FILEn\")
    -od    PATH     :    Set the main output directory. a \"scores\" 
                         subdirectory containing intermediate files will be 
                         created. 
    -tha    FLOAT    :   First list of thresholds to use. (between 0-1 for TFFM
                         matrices & between -60-0 for PWMs). Choosing 
                         thresholds can be quite complicated. One way to get
                         satisfying threshold is to set them from a scores
                         distribution (see -thf). (default: (0))
                         Example: (\"FLOAT1\" \"FLOAT2\" ... \"FLOATn\")
    -thb    FLOAT    :   Second list of thresholds to use. (between 0-1 for TFFM
                         matrices & between -60-0 for PWMs). Choosing 
                         thresholds can be quite complicated. One way to get
                         satisfying threshold is to set them from a scores
                         distribution (see -thf). (default: (0))
                         Example: (\"FLOAT1\" \"FLOAT2\" ... \"FLOATn\")

    -- optional arguments :
    -thfa   PATH     :   Set a directory path for first thresholds (output of 
                         compute_distribution function). Function will look for
                         \"scores_99_*_info.txt\" files. (default: \"null\")
    -thfb   PATH     :   Set a directory path for second thresholds (output of 
                         compute_distribution function). Function will look for
                         \"scores_99_*_info.txt\" files. (default: \"null\")
    -miny  INT      :    minimum enrichment to display on y-axis. (default: 0)
    -maxy  INT      :    maximum enrichment to display on y-axis. (default: 0)
    -maxs  INT      :    maximum spacing to compute. For dimers (using 
                         monomeric matrices), a value between 30 to 50 bp 
                         seems a good start. For tetramers (using dimeric 
                         matrices) a value between 70 to 100 bp is a good 
                         start. You may adjust those values after your first
                         results. (default: 50)
    -mins  INT      :    minimum spacing to compute. Usually set to 0. You may
                         change this value if you add offsets, this will
                         prevent huge drop off in enrichment for the first 
                         spacings computed. (default: 0)
    -ol    INT      :    offset to apply on the left of the first matrix used. 
                         This argument (in addition to -or) allows to change the
                         way spacings are counted. This may be usefull when
                         you want to count space around a consensus sequence
                         or from the center of the matrix. Please, keep in
                         mind that it might create overlaping between 
                         positions of large information content, inducing a
                         biais not taken into consideration in this analysis.
                         We therefore suggest that you avoid this case.
    -or    INT      :    offset to apply on the right of the first matrix 
                         used. See -ol option for details.
    -ol2    INT      :   offset to apply on the left of the second matrix used.
                         This argument (in addition to -or) allows to change the
                         way spacings are counted. This may be usefull when
                         you want to count space around a consensus sequence
                         or from the center of the matrix. Please, keep in
                         mind that it might create overlaping between 
                         positions of large information content, inducing a
                         biais not taken into consideration in this analysis.
                         We therefore suggest that you avoid this case.
    -or2    INT      :   offset to apply on the right of the second matrix 
                         used. See -ol option for details.
    -g     FILE     :    Fasta of the genome used as reference.
    -sym            :    Precise if the matrix used is symetric. In that case,
                         instead of usual DR, ER & IR spacing, only the 
                         spacing is reported, since the matrix is not 
                         oriented. Note that TFFM are not symetric by design,
                         and this parameter will be ignored if used with TFFM.
                         (default: asymmetric matrix)
\n";;
	spacing_TFBSTSS) 
echo -e "
==========
usage: spacing_TFBSTSS -p <LIST of FILE> -ma <LIST of FILE> -n <LIST of STRING>
       -od <RESULT_DIR> -thtf <LIST of FLOAT> -thtss <LIST of FLOAT> -f [INT]
       -w [INT] -thfa [PATH] -thfb [PATH] -maxy [INT] -miny [INT] -maxs [INT]
       -mins [INT] -ol [INT] -or [INT] -g [FILE] -ga [FILE] [-sym] 

general infos: computes spacing analysis between a PWM/TFFM matrix and 
               Transcription Start Site (TSS) from a peak file and an annotated 
               genome. The metric used to computed the enrichment and the 
               statistical relevance of the results is the Z-score (doi: 
               10.1093/nar/gki624; PMID: 15933209). We highly suggest that you 
               use multiple threshold, based on genome wide scores distribution 
               (computed in \"compute_distribution\" function), as they are a
               good starting point for this analysis. 

-- Mandatory arguments:
    -p     FILE     :    List of peak files (bed, narrowpeak format, or fasta 
                         files, or scores computed in \"compute_ROCS\" 
                         function). Example:(\"FILE1\" \"FILE2\" .. \"FILEn\")
    -ma     FILE     :   List of matrices files (either TFFM or PWM). 
                         Example: (\"FILE1\" \"FILE2\" ... \"FILEn\")
    -n     STRING   :    List of samples names for result files. 
                         (\"FILE1\" \"FILE2\" ... \"FILEn\")
    -od    PATH     :    Set the main output directory. a \"scores\" 
                         subdirectory containing intermediate files will be 
                         created. 
    -thtf    FLOAT    :  List of thresholds to use. (between 0-1 for TFFM
                         matrices & between -60-0 for PWMs). Choosing 
                         thresholds can be quite complicated. One way to get
                         satisfying threshold is to set them from a scores
                         distribution (see -thf). (default: (0))
                         Example: (\"FLOAT1\" \"FLOAT2\" ... \"FLOATn\")
    -thtss    FLOAT    : List of false thresholds to use to detect TSS. It needs
                         to be > -1 (default: ("-2" "-2" "-2"))
                         Example: (\"FLOAT1\" \"FLOAT2\" ... \"FLOATn\")

    -- optional arguments :
    -f      INT      :   The maximum distance between peaks and TSS allowed.
                         (default: 1000)
    -w      INT      :   A windows size in base paires in which detected matrix 
                         orientation are counted (default: 10).
    -thf   PATH     :    Set a directory path for matrix thresholds (output of 
                         compute_distribution function). Function will look for
                         \"scores_99_*_info.txt\" files. (default: \"null\")
    -miny  INT      :    minimum enrichment to display on y-axis. (default: 0)
    -maxy  INT      :    maximum enrichment to display on y-axis. (default: 0)
    -maxs  INT      :    maximum spacing to compute. For dimers (using 
                         monomeric matrices), a value between 30 to 50 bp 
                         seems a good start. For tetramers (using dimeric 
                         matrices) a value between 70 to 100 bp is a good 
                         start. You may adjust those values after your first
                         results. (default: 50)
    -mins  INT      :    minimum spacing to compute. Usually set to 0. You may
                         change this value if you add offsets, this will
                         prevent huge drop off in enrichment for the first 
                         spacings computed. (default: 0)
    -ol    INT      :    offset to apply on the left of the first matrix used. 
                         This argument (in addition to -or) allows to change the
                         way spacings are counted. This may be usefull when
                         you want to count space around a consensus sequence
                         or from the center of the matrix. Please, keep in
                         mind that it might create overlaping between 
                         positions of large information content, inducing a
                         biais not taken into consideration in this analysis.
                         We therefore suggest that you avoid this case.
    -or    INT      :    offset to apply on the right of the first matrix 
                         used. See -ol option for details.
    -g     FILE     :    Fasta of the genome used as reference.
    -ga    FILE     :    GFF3 of annotated genome used as reference.  
    -sym            :    Precise if the matrix used is symetric. In that case,
                         instead of usual DR, ER & IR spacing, only the 
                         spacing is reported, since the matrix is not 
                         oriented. Note that TFFM are not symetric by design,
                         and this parameter will be ignored if used with TFFM.
                         (default: asymmetric matrix)
\n";;
    add_coverage)
echo -e "
========== 
usage: add_coverage -b <LIST of FILE> -n <LIST of STRING> -t <FILE> -od <PATH> 
       -norm [STRING]

general infos: adds coverage information from a list of coverage files (with
               the corresponding list of names) to a table obtained from 
               pairwize_comparison function

-- Mandatory arguments:
    -b     FILE     :    list of bedgraph coverage files to be added to the
                         table. Example: (\"FILE1\" \"FILE2\" ... \"FILEn\")
    -n     STRING   :    list of names for each coverage file. Example:
                         (\"STRING1\" \"STRING2\" ... \"STRINGn\")
    -t     FILE     :    table from pairwize_comparison to add coverage info to
    -od    PATH     :    Set the Output directory
-- optional arguments :
    -norm  STRING   :    Chosing a normalisation option or not. (default: "NA")
                         Normalisation proposed: "RPKM" and "CPM". 
\n";;
    add_score)
echo -e "
========== 
usage: add_score -m <LIST of FILE> -n <LIST of STRING> -t <FILE> -od <PATH> 
       [-po]

general infos: adds scores information (either TFFM or PWM) from a
               list of matrices (with the corresponding list of
               names) to a table obtained from pairwize_comparison
               function.

-- Mandatory arguments:
    -m     FILE     :    list of matrix files.
    -n     STRING   :    list of names for each coverage file. Example:
                         (\"STRING1\" \"STRING2\" ... \"STRINGn\")
    -t     FILE     :    table from pairwize_comparison to add coverage info to
    -od    PATH     :    Set the Output directory
-- optional arguments :
    -po             :    Pocc mode. Uses probability of occupancy instead of 
                         best scores in function. Can help in TF has lots of
                         \"poor\" quality TFBS and not 1 very good TFBS.
\n";;
	analyze_decile)
echo -e "
========== 
usage: analyze_decile -n1 <STRING> -n2 <STRING> -o <PATH> -g <FILE> 
       -m <LIST of FILE> -t STRING [-th <FLOAT> -thf <PATH>] -ol [INT] -or [INT]
       -mins [INT] -maxs [INT] [-sym] -d [INT] -mim [INT] -mam [INT] -l [INT] 
       -nm [INT] -s [INT]

general infos: Performs a series of compute_space and compute_motifs on groups
               from a comparisons. Number of groups is user defined and along 
               the FC axis so extreme groups shall be specific groups from 
               dataset 1 or 2 while central groups shall be constituted of 
               \"common\" peaks.

-- Mandatory arguments:
    -n1    STRING :    name of dataset 1 used in pairwize_comparison
    -n2    STRING :    name of dataset 2 used in pairwize_comparison
    -o     PATH   :    path to results from pairwize_comparison
    -g     FILE   :    genome file in fasta.
    -m     FILE   :    list of matrix files as created by compute_motif
-- optional arguments :
    -t     STRING :    type of normalisation to use. Either \"RiP\" or \"RiL\".
                       (default: RiP)
    -th    FLOAT  :    list of 3 thresholds to use for spacing analysis. Either
                       this parameter or -thf must be given. (default: (0))
    -thf   PATH   :    Path to file, generated by compute_distribution, 
                       containing scores to uses as thresholds. Either this 
                       parameter or -thf must be given. (default: \"null\")
    -ol    INT    :    offset to use on left side of the given matrices for 
                       computing distances between TFBS. (default: 0)
    -or    INT    :    offset to use on right side of the given matrices for
                       computing distances between TFBS. (default: 0)
    -mins  INT    :    minimum spacing to compute. Usually set to 0. You may
                       change this value if you add offsets, this will prevent
                       huge drop off in enrichment for the first spacings 
                       computed. (default: 0)
    -maxs  INT    :    maximum spacing to compute. For dimers (using monomeric
                       matrices), a value between 30 to 50 bp seems a good 
                       start. For tetramers (using dimeric matrices) a value 
                       between 70 to 100 bp is a good start. You may adjust 
                       those values after your first results. (default: 30)
    -sym          :    Precise if the matrix used is symetric. In that case,
                       instead of usual DR, ER & IR spacing, only the spacing is
                       reported, since the matrix is not oriented. Note that 
                       TFFM are not symetric by design, and this parameter will
                       be ignored if used with TFFM. (default: ASYMMETRIC)
    -d     INT    :    Number of times the cloud of dots from 
                       pairwize_comparison function should be divided. Division
                       are made along the FC axis. (default: 10)
    -mim   INT    :    Minimum length of motif found by compute_motif 
                       (default: 5)
    -mam   INT    :    Maximum length of motif found by compute_motif 
                       (default: 30)
    -l    INT     :    Size of learning set for compute_motif 
                       (default: 600)
    -nm    INT     :    Number of motifs to find by compute_motif 
                       (default: 5)
    -s    INT     :    Seed for random generator in compute_motif 
                       (default: 42)
\n";;
	cooking_meth)
echo -e "
==========
usage: cooking_meth -p <FILE> -m <FILE> -n <STRING>
       -sym <STRING> -o <PATH> -g [FILE] -l [INT] -c [INT]
       -c2 [INT] -thf [PATH]

general infos: From peaks coverage file and for a given matrix, this function 
               will compare ampDAP-seq and DAP-seq peaks coverage fold change,
               providing insights into the impact of DNA methylation on TF 
               binding, at base paire resolution in TF of interest motif. 

-- Mandatory arguments:
    -p      FILE    :    Peaks coverage file of a DAP-seq and a ampDAP-seq
                         experiment (output of pairwize_comparison function).
                         Expected file in .tsv with at least 7 columns: chr,
                         start, end, covDAP and covampDAP.
    -m      FILE    :    Set the PFM matrix file of your TF of
                         interest.
    -n      STRING  :    Set the name for the output
                         architecture (used to search the
                         threshold in the Scores_Distribution
                         folder and to name output files).
    -sym    STRING  :    Set to \"yes\" or \"no\" to specify
                         whether the PFM is symmetric.
                         (default: no)
    -o      PATH    :    Set the Output directory where
                         results will be stored.

-- optional arguments :
    -g      FILE    :    Set the path to the genome FASTA
                         file.
    -l      INT     :    Set the motif length.
    -c      INT     :    Set a manual TFBS detection cutoff,
                         used during PFM search under peaks,
                         instead of the one from
                         Scores_Distribution. (default: 0, not
                         set)
    -c2     INT     :    Set a manual TFBS detection cutoff,
                         used during R statistics, instead of
                         the one from Scores_Distribution.
                         (default: 0, not set)
    -thf    PATH    :    Set the thresholds directory to use
                         for TFBS prediction. If not set, the
                         function searches for it in the
                         Scores_Distribution folder. (default:
                         null)
\n";;
	*)
echo -e "
usage: call one of the function below to see more details about this specific
       function
example: usage mapping_Fastq_bowtie2

--functions implemented:
mapping_Fastq_bowtie2   :  compute mapping and filtering (PCR duplications,
                           poor mapping quality, multimapping removed) steps.
main_mapping_Fastq      :  directory and file preparation for mapping step.
peakcalling_MACS2       :  peak calling step and filtration 
                           (forbidden regions).
peakcalling_MACS3       :  perform peak calling and peak filtration (forbidden 
                           regions). Use MACS3 as the peak caller and as some 
                           updated filtering system for unwanted peaks.
peakcalling_GOPeaks     :  perform peak calling and peak filtration (forbidden 
                           regions). Use GOPeaks as the peak caller. GOPeaks is
                           especially suited for Cut&Tag and Cut&Run data. 
main_peakcalling        :  file/directory preparation, peakcallings functions
                           (MACS2, MACS3 or GOPeaks) launching, Multiple Sample
                           Peak Calling (MSPC) procedure, union of coverages, 
                           peak resizing.
replicates_comparisons  :  comparison of peaks coverage from replicates on the 
                           consensus peaks determined by the peakcalling_MACS2
                           function.
pairwize_comparison      :  comparison of 2 samples/replicats, filtering
                           (optional) by height of maximum or global peak
                           coverages, plot of the union of peaks depending of
                           both coverages, peak reattribution according to CFR
                           (and not according to peak caller; plots with both
                           for comparison). 
                           CFR: coverages fold ratio; CFC (used in plots): 
                           coverages fold change.
compute_rpkmrip_rpkmril :  Takes a bed file with peaks coordinates 
                           (e.g. merged peaks of two conditions yield by 
						   pairwize_comparison) to recalculate normalized RPKM
						   for each sample you provided in 'sn'.			   
compute_motif           :  PWM and TFFM motif generation using learning set
                           (creation of testing set for later use).
prep_annotation         :  preparation of annotation file necessary for 
                           negative set generation. Modification of gff file
                           (adding intergenic, promoter regions).
compute_NS              :  creation of negative sets (for ROCs and spacing 
                           analysis). Negative sequences are created to be the
                           closest possible to the \"positive\" sequences (the
                           peaks), negative sequences must originate from the
                           same type of regions (promoters, exon, intergenic,
                           etc), have a GC percentage as close as possible and
                           not be bound (not in the positive sequences).
generate_weighted_fasta :  a function called by compute_kmer to generate a 
                           fasta where each sequence (peak) is weighted 
						   (written in the header name). The weight can be 
						   the coverage value (RPKM). This weight can be used
						   by the KMAC tool in compute_kmer.
compute_kmer            :  Use the KMAC tool (Guo et al. 2018 Genome Res.) 
                           to compute Kmer Set Memory (KSM): sets of over-
						   represented sequences relative to another set 
						   (option b2) or relative to a bunch of sets (e.g. 
						   several negative sets) (option pns). This b2 and 
						   pns options may look poorly coded but pns is meant 
						   to keep aside one of the negative (unbound) 
						   sequence that will be used in the compute_ROC function.
compute_ROCS            :  computes scores for PWM/TFFM on negative sequences
                           and peaks. compute ROCs and AUCROC from those 
                           scores.
compute_space           :  computes spacing analysis on peak files using PWM
                           or TFFM.
spacing_2TFs            :  computes spacing analysis on peak files between
                           paires set of PWM or TFFM 
spacing_TFBSTSS         :  computes spacing analysis relative to TSSs location
                           on peaks files using PWM or TFFM.
compute_DNAshape        :  Generate a .pkl model from TFFM taking into account 
                           DNA structural informations (Mathelier et al., 2017)
compute_SeqConv         :  Generate a .keras model containing a Convolutional
                           Neural Network trained on a peaks file. 
                           (Shen et al., 2021).
compute_distribution    :  With a given matrice (PWM/TFFM), compute scores 
                           along the genome of your choice to get their 
                           distribution 
analyze_decile          :  Performs a series of compute_space and compute_motifs
                           on groups from a comparisons. Number of groups is 
                           user defined and along the FC axis so extreme groups
                           shall be specific groups from dataset 1 or 2 while
                           central groups shall be constituted of \"common\"
                           peaks.
spacing_impact          :  creates a plot showing the relation of the ratio of
                           coverages and the presence of some specific spacing
add_coverage            :  adds coverage information from a list of coverage
                           files (with the corresponding list of names) to a
                           table obtained from pairwize_comparison function.
add_score               :  adds scores information (either TFFM or PWM) from a
                           list of matrices (with the corresponding list of
                           names) to a table obtained from pairwize_comparison
                           function.
cooking_meth            :  Assess the effect of methylcytosines on the 
                           TF relative binding intensity in a DAP-seq versus
                           an amplified DAP-seq experiment. Effect is assessed
                           in the bound region, in the best TFBS and at each
                           position in the best TFBS. As described in Lai et 
                           al 2021 Molecular Plant 2021.

created by Stigliani A. ; Lucas J. ; Blanc-Mathieu R. ; Parcy F.
assembled by Lucas J. ; Jegou A. ; Blanc-Mathieu R.
\n";;
	esac
echo -e "==========\n"
}













